name: aikitchen
description: "Aplicacion de recetas usando la IA de google"
publish_to: "none"
version: 2.8.0+54

environment:
  sdk: ^3.8.0

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3
  fluttertoast: ^9.0.0
  home_widget: ^0.8.0
  html: ^0.15.4
  path_provider: ^2.1.5
  receive_sharing_intent: ^1.4.5
  share_plus: ^12.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  http: ^1.2.0
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.9.0
  file_picker: ^10.3.10
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
